# Generated by Django 4.0.3 on 2022-03-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
